version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-244-254.compute-1.amazonaws.com
            port: '5432'
            database: ded2mb64ob53k1
            user: qtmewnorwwckcc
            password: 181be9336694e18ffe99d4ddfd6d8b983e9e83ff68ef1d492ff5c647a999c328
            migrations: true
            rawAccess: true