version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-224-157.compute-1.amazonaws.com
            port: '5432'
            database: deaddah0amvsej
            ssl: true
            user: nryjzdswmfgeuk
            password: 845af020c81641d028f96371a05dda361076f91b9b59aeb5c514632ddc58e9ca
            migrations: true
